2021/02/20 11:30:53 Ass_main.py[line:68] INFO ######## Tools start ########
2021/02/20 11:30:53 Ass_main.py[line:165] INFO ######>>> Check device
2021/02/20 11:30:54 Ass_main.py[line:180] DEBUG Device list:[]
2021/02/20 11:30:54 Ass_main.py[line:432] INFO ######>>> Check port
2021/02/20 11:30:54 Ass_main.py[line:440] DEBUG Port list:{'COM1': '通信端口 (COM1)', 'COM3': 'LeadCore CMCC Diagnoses (COM3)', 'COM8': 'LeadCore CMCC AT Interface (COM8)'}
2021/02/20 11:30:54 Ass_main.py[line:913] INFO ######>>> Init settings AT Dialog
2021/02/20 11:30:54 Ass_main.py[line:980] INFO ######>>> Init Default settings Dialog
2021/02/20 11:30:59 Ass_main.py[line:446] INFO ######>>> Open port
2021/02/20 11:30:59 Ass_main.py[line:449] INFO Port:COM8  baudrate:115200  bytesize:8  parity:N  stopbits:1
2021/02/20 11:31:01 Ass_main.py[line:465] INFO ######>>> Close port
2021/02/20 11:31:05 Ass_main.py[line:446] INFO ######>>> Open port
2021/02/20 11:31:05 Ass_main.py[line:449] INFO Port:COM8  baudrate:115200  bytesize:8  parity:N  stopbits:1
2021/02/20 11:31:06 Ass_main.py[line:692] DEBUG calling_to_answer
2021/02/20 11:31:06 Ass_main.py[line:718] DEBUG test times:3
2021/02/20 11:31:08 Ass_main.py[line:465] INFO ######>>> Close port
2021/02/20 11:31:30 Ass_main.py[line:119] WARNING force stop test !!!
2021/02/20 11:31:33 Ass_main.py[line:119] WARNING force stop test !!!
2021/02/20 11:31:37 Ass_main.py[line:576] DEBUG test flag:True
2021/02/20 11:31:54 Ass_main.py[line:446] INFO ######>>> Open port
2021/02/20 11:31:54 Ass_main.py[line:449] INFO Port:COM8  baudrate:115200  bytesize:8  parity:N  stopbits:1
2021/02/20 11:32:05 Ass_main.py[line:465] INFO ######>>> Close port
2021/02/20 11:32:06 Ass_main.py[line:446] INFO ######>>> Open port
2021/02/20 11:32:06 Ass_main.py[line:449] INFO Port:COM8  baudrate:115200  bytesize:8  parity:N  stopbits:1
2021/02/20 11:32:07 Ass_main.py[line:499] INFO Send choose at  ./:AT
2021/02/20 11:32:07 Ass_main.py[line:537] DEBUG Receive data:
OK

2021/02/20 11:32:08 Ass_main.py[line:499] INFO Send choose at  ./:AT
2021/02/20 11:32:08 Ass_main.py[line:537] DEBUG Receive data:
OK

2021/02/20 11:32:08 Ass_main.py[line:499] INFO Send choose at  ./:AT
2021/02/20 11:32:08 Ass_main.py[line:537] DEBUG Receive data:
OK

2021/02/20 11:32:15 Ass_main.py[line:537] DEBUG Receive data:
^DGSQU: 14,1

+CSQ: 14,1

^SATSIGNAL:-125,47

2021/02/20 11:32:15 Ass_main.py[line:537] DEBUG Receive data:
^CPSTATE: -125,381,37,84

2021/02/20 11:32:33 Ass_main.py[line:119] WARNING force stop test !!!
2021/02/20 11:32:35 Ass_main.py[line:686] DEBUG no_caller_answer
2021/02/20 11:32:35 Ass_main.py[line:862] DEBUG test times:1
2021/02/20 11:32:37 Ass_main.py[line:584] INFO exec >> ATD18701997306;
2021/02/20 11:32:37 Ass_main.py[line:870] INFO 主叫未接 >> 第1次, 共1次,
2021/02/20 11:32:37 Ass_main.py[line:537] DEBUG Receive data:
OK

NO CARRIER

^SATSIGNAL:-109,73

^CPSTATE: -109,381,37,84

2021/02/20 11:32:40 Ass_main.py[line:875] DEBUG dial process: []
2021/02/20 11:32:40 Ass_main.py[line:887] ERROR 拨打失败，请检查是被是否入网
2021/02/20 11:32:40 Ass_main.py[line:898] INFO 测试项：主叫未接 测试次数:0, pass:0, fail:1

2021/02/20 11:32:45 Ass_main.py[line:686] DEBUG no_caller_answer
2021/02/20 11:32:45 Ass_main.py[line:862] DEBUG test times:1
2021/02/20 11:32:46 Ass_main.py[line:537] DEBUG Receive data:
^DGSQU: 30,2

+CSQ: 30,2

2021/02/20 11:32:46 Ass_main.py[line:119] WARNING force stop test !!!
2021/02/20 11:32:47 Ass_main.py[line:584] INFO exec >> ATD18701997306;
2021/02/20 11:32:47 Ass_main.py[line:870] INFO 主叫未接 >> 第1次, 共1次,
2021/02/20 11:32:47 Ass_main.py[line:537] DEBUG Receive data:
OK

NO CARRIER

2021/02/20 11:32:50 Ass_main.py[line:875] DEBUG dial process: []
2021/02/20 11:32:50 Ass_main.py[line:887] ERROR 拨打失败，请检查是被是否入网
2021/02/20 11:32:50 Ass_main.py[line:898] INFO 测试项：主叫未接 测试次数:0, pass:0, fail:1

2021/02/20 11:32:52 Ass_main.py[line:499] INFO Send choose at  ./:AT
2021/02/20 11:32:52 Ass_main.py[line:537] DEBUG Receive data:
OK

2021/02/20 11:32:54 Ass_main.py[line:465] INFO ######>>> Close port
2021/02/20 11:32:55 Ass_main.py[line:446] INFO ######>>> Open port
2021/02/20 11:32:55 Ass_main.py[line:449] INFO Port:COM8  baudrate:115200  bytesize:8  parity:N  stopbits:1
2021/02/20 11:32:56 Ass_main.py[line:686] DEBUG no_caller_answer
2021/02/20 11:32:56 Ass_main.py[line:862] DEBUG test times:1
2021/02/20 11:32:58 Ass_main.py[line:584] INFO exec >> ATD18701997306;
2021/02/20 11:32:58 Ass_main.py[line:870] INFO 主叫未接 >> 第1次, 共1次,
2021/02/20 11:32:58 Ass_main.py[line:537] DEBUG Receive data:
OK

2021/02/20 11:32:58 Ass_main.py[line:537] DEBUG Receive data:
NO CARRIER

^SATSIGNAL:-108,90

^CPSTATE: -108,381,37,84

2021/02/20 11:33:01 Ass_main.py[line:875] DEBUG dial process: []
2021/02/20 11:33:01 Ass_main.py[line:887] ERROR 拨打失败，请检查是被是否入网
2021/02/20 11:33:01 Ass_main.py[line:898] INFO 测试项：主叫未接 测试次数:0, pass:0, fail:1

2021/02/20 11:33:08 Ass_main.py[line:678] DEBUG caller_hangs_up
2021/02/20 11:33:08 Ass_main.py[line:769] DEBUG test times:1
2021/02/20 11:33:10 Ass_main.py[line:465] INFO ######>>> Close port
