2021/02/20 11:09:34 Ass_main.py[line:68] INFO ######## Tools start ########
2021/02/20 11:09:34 Ass_main.py[line:165] INFO ######>>> Check device
2021/02/20 11:09:34 Ass_main.py[line:180] DEBUG Device list:[]
2021/02/20 11:09:34 Ass_main.py[line:429] INFO ######>>> Check port
2021/02/20 11:09:34 Ass_main.py[line:437] DEBUG Port list:{'COM1': '通信端口 (COM1)', 'COM3': 'LeadCore CMCC Diagnoses (COM3)', 'COM8': 'LeadCore CMCC AT Interface (COM8)'}
2021/02/20 11:09:34 Ass_main.py[line:906] INFO ######>>> Init settings AT Dialog
2021/02/20 11:09:34 Ass_main.py[line:973] INFO ######>>> Init Default settings Dialog
2021/02/20 11:09:39 Ass_main.py[line:443] INFO ######>>> Open port
2021/02/20 11:09:39 Ass_main.py[line:446] INFO Port:COM8  baudrate:115200  bytesize:8  parity:N  stopbits:1
2021/02/20 11:09:41 Ass_main.py[line:119] WARNING force stop test !!!
2021/02/20 11:09:51 Ass_main.py[line:533] DEBUG Receive data:
^DGSQU: 30,2

+CSQ: 30,2

^SATSIGNAL:-109,75

^CPSTATE: -109,381,37,84

2021/02/20 11:09:51 Ass_main.py[line:533] DEBUG Receive data:
^DGSQU: 30,2

2021/02/20 11:09:51 Ass_main.py[line:533] DEBUG Receive data:
+CSQ: 30,2

2021/02/20 11:10:22 Ass_main.py[line:533] DEBUG Receive data:
^DGSQU: 13,0

+CSQ: 13,0

^SATSIGNAL:-126,34

2021/02/20 11:10:22 Ass_main.py[line:533] DEBUG Receive data:
^CPSTATE: -126,381,37,84

2021/02/20 11:10:23 Ass_main.py[line:685] DEBUG calling_to_answer
2021/02/20 11:10:23 Ass_main.py[line:711] DEBUG test times:3
2021/02/20 11:10:25 Ass_main.py[line:577] INFO exec >> ATD18701997306;
2021/02/20 11:10:25 Ass_main.py[line:720] INFO 主叫接听 >> 第1次, 共3次,
2021/02/20 11:10:25 Ass_main.py[line:533] DEBUG Receive data:
ERROR

2021/02/20 11:10:28 Ass_main.py[line:726] DEBUG dial process: []
2021/02/20 11:10:28 Ass_main.py[line:738] ERROR 拨打失败，请检查设备是否入网
2021/02/20 11:10:28 Ass_main.py[line:751] INFO 测试项：主叫接听 测试次数:1, pass:0, fail:1

2021/02/20 11:10:32 Ass_main.py[line:685] DEBUG calling_to_answer
2021/02/20 11:10:32 Ass_main.py[line:711] DEBUG test times:3
2021/02/20 11:10:33 Ass_main.py[line:119] WARNING force stop test !!!
2021/02/20 11:10:34 Ass_main.py[line:577] INFO exec >> ATD18701997306;
2021/02/20 11:10:34 Ass_main.py[line:720] INFO 主叫接听 >> 第1次, 共3次,
2021/02/20 11:10:34 Ass_main.py[line:533] DEBUG Receive data:
ERROR

2021/02/20 11:10:36 Ass_main.py[line:751] INFO 测试项：主叫接听 测试次数:1, pass:0, fail:0

2021/02/20 11:10:53 Ass_main.py[line:533] DEBUG Receive data:
^DGSQU: 30,2

+CSQ: 30,2

^SATSIGNAL:-109,72

2021/02/20 11:10:53 Ass_main.py[line:533] DEBUG Receive data:
^CPSTATE: -109,381,37,84

2021/02/20 11:11:23 Ass_main.py[line:533] DEBUG Receive data:
^DGSQU: 29,2

+CSQ: 29,2

2021/02/20 11:11:23 Ass_main.py[line:533] DEBUG Receive data:
^SATSIGNAL:-110,61

^CPSTATE: -110,381,37,84

2021/02/20 11:11:54 Ass_main.py[line:533] DEBUG Receive data:
^DGSQU: 13,1

+CSQ: 13,1

^SATSIGNAL:-126,54

2021/02/20 11:11:54 Ass_main.py[line:533] DEBUG Receive data:
^CPSTATE: -126,381,37,84

2021/02/20 11:12:24 Ass_main.py[line:533] DEBUG Receive data:
^DGSQU: 13,0

+CSQ: 13,0

2021/02/20 11:12:55 Ass_main.py[line:533] DEBUG Receive data:
^DGSQU: 13,1

+CSQ: 13,1

2021/02/20 11:14:28 Ass_main.py[line:533] DEBUG Receive data:
^DGSQU: 31,3

+CSQ: 31,3

^SATSIGNAL:-108,86

2021/02/20 11:14:28 Ass_main.py[line:533] DEBUG Receive data:
^CPSTATE: -108,381,37,84

2021/02/20 11:14:58 Ass_main.py[line:533] DEBUG Receive data:
^DGSQU: 31,3

+CSQ: 31,3

2021/02/20 11:15:59 Ass_main.py[line:533] DEBUG Receive data:
^DGSQU: 30,2

+CSQ: 30,2

2021/02/20 11:15:59 Ass_main.py[line:533] DEBUG Receive data:
^SATSIGNAL:-109,74

^CPSTATE: -109,381,37,84

2021/02/20 11:16:00 Ass_main.py[line:533] DEBUG Receive data:
^DGSQU: 30,2

+CSQ: 30,2

2021/02/20 11:16:30 Ass_main.py[line:533] DEBUG Receive data:
^DGSQU: 31,2

+CSQ: 31,2

2021/02/20 11:16:30 Ass_main.py[line:533] DEBUG Receive data:
^SATSIGNAL:-108,74

^CPSTATE: -108,381,37,84

2021/02/20 11:17:01 Ass_main.py[line:533] DEBUG Receive data:
^DGSQU: 30,2

2021/02/20 11:17:01 Ass_main.py[line:533] DEBUG Receive data:
+CSQ: 30,2

^SATSIGNAL:-109,74

^CPSTATE: -109,381,37,84

2021/02/20 11:17:32 Ass_main.py[line:533] DEBUG Receive data:
^DGSQU: 31,2

2021/02/20 11:17:32 Ass_main.py[line:533] DEBUG Receive data:
+CSQ: 31,2

^SATSIGNAL:-108,66

^CPSTATE: -108,381,37,84

2021/02/20 11:17:57 Ass_main.py[line:711] DEBUG test times:5
2021/02/20 11:17:59 Ass_main.py[line:577] INFO exec >> ATD18701997306;
2021/02/20 11:17:59 Ass_main.py[line:720] INFO 主叫接听 >> 第1次, 共5次,
2021/02/20 11:17:59 Ass_main.py[line:533] DEBUG Receive data:
ERROR

2021/02/20 11:18:02 Ass_main.py[line:685] DEBUG calling_to_answer
2021/02/20 11:18:02 Ass_main.py[line:711] DEBUG test times:3
2021/02/20 11:18:02 Ass_main.py[line:726] DEBUG dial process: []
2021/02/20 11:18:02 Ass_main.py[line:738] ERROR 拨打失败，请检查设备是否入网
2021/02/20 11:18:02 Ass_main.py[line:751] INFO 测试项：主叫接听 测试次数:1, pass:0, fail:1

2021/02/20 11:18:03 Ass_main.py[line:533] DEBUG Receive data:
^DGSQU: 31,3

2021/02/20 11:18:03 Ass_main.py[line:533] DEBUG Receive data:
+CSQ: 31,3

2021/02/20 11:18:04 Ass_main.py[line:577] INFO exec >> ATD18701997306;
2021/02/20 11:18:04 Ass_main.py[line:720] INFO 主叫接听 >> 第2次, 共3次,
2021/02/20 11:18:04 Ass_main.py[line:533] DEBUG Receive data:
ERROR

2021/02/20 11:18:06 Ass_main.py[line:751] INFO 测试项：主叫接听 测试次数:1, pass:0, fail:0

2021/02/20 11:18:33 Ass_main.py[line:533] DEBUG Receive data:
^DGSQU: 13,1

+CSQ: 13,1

^SATSIGNAL:-126,51

^CPSTATE: -126,381,37,84

2021/02/20 11:19:04 Ass_main.py[line:533] DEBUG Receive data:
^DGSQU: 31,3

+CSQ: 31,3

2021/02/20 11:19:04 Ass_main.py[line:533] DEBUG Receive data:
^SATSIGNAL:-108,84

^CPSTATE: -108,381,37,84

2021/02/20 11:19:35 Ass_main.py[line:533] DEBUG Receive data:
^DGSQU: 31,3

2021/02/20 11:19:35 Ass_main.py[line:533] DEBUG Receive data:
+CSQ: 31,3

2021/02/20 11:20:05 Ass_main.py[line:533] DEBUG Receive data:
^DGSQU: 31,2

+CSQ: 31,2

2021/02/20 11:20:36 Ass_main.py[line:533] DEBUG Receive data:
^DGSQU: 14,1

+CSQ: 14,1

^SATSIGNAL:-125,58

2021/02/20 11:20:36 Ass_main.py[line:533] DEBUG Receive data:
^CPSTATE: -125,381,37,84

2021/02/20 11:21:07 Ass_main.py[line:533] DEBUG Receive data:
^DGSQU: 13,1

+CSQ: 13,1

^SATSIGNAL:-126,51

2021/02/20 11:21:07 Ass_main.py[line:533] DEBUG Receive data:
^CPSTATE: -126,381,37,84

2021/02/20 11:21:39 Ass_main.py[line:533] DEBUG Receive data:
^DGSQU: 29,2

+CSQ: 29,2

^SATSIGNAL:-110,67

^CPSTATE: -110,381,37,84

2021/02/20 11:22:10 Ass_main.py[line:533] DEBUG Receive data:
^DGSQU: 30,2

+CSQ: 30,2

^SATSIGNAL:-109,72

2021/02/20 11:22:10 Ass_main.py[line:533] DEBUG Receive data:
^CPSTATE: -109,381,37,84

2021/02/20 11:22:40 Ass_main.py[line:533] DEBUG Receive data:
^DGSQU: 12,0

+CSQ: 12,0

2021/02/20 11:22:41 Ass_main.py[line:533] DEBUG Receive data:
^SATSIGNAL:-127,33

^CPSTATE: -127,381,37,84

2021/02/20 11:23:12 Ass_main.py[line:533] DEBUG Receive data:
^DGSQU: 13,0

+CSQ: 13,0

^SATSIGNAL:-126,39

2021/02/20 11:23:12 Ass_main.py[line:533] DEBUG Receive data:
^CPSTATE: -126,381,37,84

